"""initialize databases

Revision ID: 43de0465c856
Revises:
Create Date: 2020-09-08 15:16:03.902989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "43de0465c856"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
