"""Initializing the database

Revision ID: 584ca546aada
Revises:
Create Date: 2020-09-08 12:54:45.273210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "584ca546aada"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
