"""initialize databases

Revision ID: 93886fe12b77
Revises: 43de0465c856
Create Date: 2020-09-08 15:16:27.577523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "93886fe12b77"
down_revision = "43de0465c856"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
