"""password field updated

Revision ID: 9891c5718ddf
Revises: 7f5de60a0e02
Create Date: 2020-09-08 15:18:54.636595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9891c5718ddf"
down_revision = "7f5de60a0e02"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(), nullable=True))
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("users", "password")
    # ### end Alembic commands ###
