"""Initializing the database

Revision ID: e008510f4bb9
Revises: 584ca546aada
Create Date: 2020-09-08 13:00:02.125650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e008510f4bb9"
down_revision = "584ca546aada"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "league",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("division", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("disabled", sa.Boolean(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "fantasyteam",
        sa.Column("fid", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["fid"], ["users.id"]),
        sa.PrimaryKeyConstraint("fid"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "team",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("stadium", sa.String(), nullable=True),
        sa.Column("league_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["league_id"], ["league.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("stadium"),
    )
    op.create_table(
        "player",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("nationality", sa.String(), nullable=True),
        sa.Column("kit_no", sa.String(), nullable=True),
        sa.Column("dominant_foot", sa.String(), nullable=True),
        sa.Column("fantasy_price", sa.Float(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fantasy_players",
        sa.Column("fantasy_team_id", sa.Integer(), nullable=True),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["fantasy_team_id"], ["fantasyteam.fid"]),
        sa.ForeignKeyConstraint(["player_id"], ["player.id"]),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fantasy_players")
    op.drop_table("player")
    op.drop_table("team")
    op.drop_table("fantasyteam")
    op.drop_table("users")
    op.drop_table("league")
    # ### end Alembic commands ###
